'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const S = require('./core.js');
const t = (name = 'read', annotations = { readOnlyHint: true, openWorldHint: false }) => ({ name, description: 'Read a record', inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] }, annotations });
const snap = tools => S.parseSnapshot(JSON.stringify({ tools }));
const diff = (a, b) => S.compare(snap(a), snap(b));
const clone = x => JSON.parse(JSON.stringify(x));
const code = (r, c) => r.entries.some(e => e.notes.some(n => n.code === c));

test('accept tools/list result', () => assert.equal(S.parseSnapshot(JSON.stringify({ jsonrpc: '2.0', id: 1, result: { tools: [t()] } })).tools.length, 1));
test('accept 2026 complete result wrapper', () => assert.equal(S.parseSnapshot(JSON.stringify({ result: { resultType: 'complete', tools: [t()] } })).tools.length, 1));
test('accept bare array', () => assert.equal(S.parseSnapshot(JSON.stringify([t()])).tools.length, 1));
test('empty inventories are valid', () => assert.deepEqual(diff([], []).counts, { added: 0, removed: 0, changed: 0, unchanged: 0, review: 0 }));
test('identical tools are unchanged', () => assert.equal(diff([t()], [t()]).counts.unchanged, 1));
test('object key order is insignificant', () => { const a = t(), b = { annotations: a.annotations, inputSchema: a.inputSchema, description: a.description, name: a.name }; assert.equal(diff([a], [b]).counts.unchanged, 1); });
test('required order is insignificant', () => { const a = t(), b = t(); a.inputSchema.required = ['id', 'format']; b.inputSchema.required = ['format', 'id']; assert.equal(diff([a], [b]).counts.unchanged, 1); });
test('enum order is insignificant', () => { const a = t(), b = t(); a.inputSchema.properties.id.enum = ['b', 'a']; b.inputSchema.properties.id.enum = ['a', 'b']; assert.equal(diff([a], [b]).counts.unchanged, 1); });
test('reports additions and removals', () => { const r = diff([t('old')], [t('new')]); assert.equal(r.counts.added, 1); assert.equal(r.counts.removed, 1); assert.equal(r.counts.review, 2); });
test('read only to write declaration', () => assert.ok(code(diff([t()], [t('read', { readOnlyHint: false })]), 'WRITE_DECLARATION')));
test('missing read-only hint uses pessimistic default', () => { const b = t(); delete b.annotations; const r = diff([t()], [b]); assert.ok(code(r, 'WRITE_DECLARATION')); assert.equal(r.entries[0].after.missing.length, 4); });
test('explicit false and omitted default remain distinguishable', () => { const a = t('read', {}), b = t('read', { readOnlyHint: false }); assert.equal(diff([a], [b]).counts.changed, 1); });
test('destructive hint only flagged for non-read-only candidate', () => { const a = t('read', { readOnlyHint: true, destructiveHint: false }), b = t('read', { readOnlyHint: true, destructiveHint: true }); assert.equal(code(diff([a], [b]), 'DESTRUCTIVE_DECLARATION'), false); });
test('newly destructive declaration', () => assert.ok(code(diff([t('write', { readOnlyHint: false, destructiveHint: false })], [t('write', { readOnlyHint: false, destructiveHint: true })]), 'DESTRUCTIVE_DECLARATION')));
test('external scope declaration', () => assert.ok(code(diff([t()], [t('read', { readOnlyHint: true, openWorldHint: true })]), 'OPEN_WORLD_DECLARATION')));
test('retry declaration removed', () => assert.ok(code(diff([t('write', { readOnlyHint: false, idempotentHint: true })], [t('write', { readOnlyHint: false, idempotentHint: false })]), 'RETRY_DECLARATION')));
test('new required input', () => { const b = t(); b.inputSchema.required.push('format'); b.inputSchema.properties.format = { type: 'string' }; assert.ok(code(diff([t()], [b]), 'REQUIRED_ADDED')); });
test('input property removed', () => { const b = t(); delete b.inputSchema.properties.id; b.inputSchema.required = []; assert.ok(code(diff([t()], [b]), 'PROPERTY_REMOVED')); });
test('input type changed', () => { const b = t(); b.inputSchema.properties.id.type = 'integer'; assert.ok(code(diff([t()], [b]), 'PROPERTY_TYPE')); });
test('enum narrowed', () => { const a = t(), b = t(); a.inputSchema.properties.id.enum = ['a', 'b']; b.inputSchema.properties.id.enum = ['a']; assert.ok(code(diff([a], [b]), 'ENUM_NARROWED')); });
test('enum expanded is not narrowing', () => { const a = t(), b = t(); a.inputSchema.properties.id.enum = ['a']; b.inputSchema.properties.id.enum = ['a', 'b']; assert.equal(code(diff([a], [b]), 'ENUM_NARROWED'), false); });
test('nested schema edits still reported', () => { const b = t(); b.inputSchema.properties.id.minLength = 4; assert.ok(code(diff([t()], [b]), 'INPUT_SCHEMA')); });
test('output schema edits reported', () => { const b = t(); b.outputSchema = { type: 'object', properties: {} }; assert.ok(code(diff([t()], [b]), 'OUTPUT_SCHEMA')); });
test('description edits reported without safety scoring', () => { const b = t(); b.description = 'Different instructions'; const r = diff([t()], [b]); assert.ok(code(r, 'DESCRIPTION')); assert.equal(r.counts.review, 0); });
test('unknown metadata edits are not ignored', () => { const b = t(); b.execution = { taskSupport: 'optional' }; assert.ok(code(diff([t()], [b]), 'METADATA')); });
test('duplicate names within one server rejected', () => assert.throws(() => snap([t(), t()]), S.SnapshotError));
test('same name in different servers preserved', () => assert.equal(S.parseSnapshot(JSON.stringify({ servers: [{ name: 'a', tools: [t()] }, { name: 'b', tools: [t()] }] })).tools.length, 2));
test('duplicate server names rejected', () => assert.throws(() => S.parseSnapshot(JSON.stringify({ servers: [{ name: 'a', tools: [] }, { name: 'a', tools: [] }] })), S.SnapshotError));
test('server and tool separators cannot collide', () => { const a = S.parseSnapshot(JSON.stringify({ servers: [{ name: 'x/y', tools: [t('z')] }, { name: 'x', tools: [t('y/z')] }] })); assert.equal(new Set(a.tools.map(t => t.key)).size, 2); });
for (const [name, text] of [ ['empty text', ''], ['bad json', '{'], ['null', 'null'], ['string', '"hello"'], ['config not inventory', '{"mcpServers":{}}'], ['RPC error', '{"error":{"code":1}}'], ['incomplete page', '{"tools":[],"nextCursor":"more"}'], ['empty cursor still incomplete', '{"tools":[],"nextCursor":""}'], ['pending response', '{"result":{"resultType":"input_required","tools":[]}}'], ['invalid tool', '{"tools":[null]}'] ]) test('reject ' + name, () => assert.throws(() => S.parseSnapshot(text), S.SnapshotError));
test('nested pagination rejected', () => assert.throws(() => S.parseSnapshot('{"servers":[{"name":"a","tools":[],"nextCursor":"x"}]}'), S.SnapshotError));
test('string hint not coerced to boolean', () => assert.throws(() => snap([t('read', { readOnlyHint: 'false' })]), S.SnapshotError));
test('null hint rejected', () => assert.throws(() => snap([t('read', { readOnlyHint: null })]), S.SnapshotError));
test('missing input schema rejected', () => { const a = t(); delete a.inputSchema; assert.throws(() => snap([a]), S.SnapshotError); });
test('wrong root schema rejected', () => { const a = t(); a.inputSchema.type = 'string'; assert.throws(() => snap([a]), S.SnapshotError); });
test('duplicate required properties rejected', () => { const a = t(); a.inputSchema.required = ['id', 'id']; assert.throws(() => snap([a]), S.SnapshotError); });
test('control characters in names rejected', () => assert.throws(() => snap([t('x\ny')]), S.SnapshotError));
test('oversized input rejected', () => assert.throws(() => S.parseSnapshot(' '.repeat(S.LIMITS.bytes + 1) + '[]'), S.SnapshotError));
test('tool count bounded', () => assert.throws(() => snap(Array.from({ length: 501 }, (_, i) => t('tool-' + i))), S.SnapshotError));
test('deep nesting bounded', () => { const a = t(); let n = a; for (let i = 0; i < 52; i++) n = n.child = {}; assert.throws(() => snap([a]), S.SnapshotError); });
test('prototype keys handled as inert data', () => { const a = t('__proto__'); a.inputSchema = JSON.parse('{"type":"object","properties":{"__proto__":{"type":"string"}}}'); const b = clone(a); b.description = 'changed'; assert.equal(diff([a], [b]).counts.changed, 1); assert.equal({}.polluted, undefined); });
test('comparison does not mutate original inputs', () => { const a = snap([t()]), b = snap([t('new')]); const text = JSON.stringify([a, b]); S.compare(a, b); assert.equal(JSON.stringify([a, b]), text); });
test('export includes raw changes and disclaimer', () => { const r = S.exportReport(diff([], [t()])); assert.equal(r.changes[0].after.name, 'read'); assert.match(r.disclaimer, /Not a security audit/); assert.equal(r.format, 'scopediff-report-v1'); });
test('markdown does not include raw descriptions or executable HTML', () => { const a = t('<script>alert(1)</script>'); a.description = '<img src=x onerror=alert(1)>'; const report = S.markdownReport(diff([], [a])); assert.ok(!report.includes('<script>')); assert.ok(!report.includes('<img')); });
test('all counts account for union', () => { const r = diff([t('same'), t('gone'), t('change')], [t('same'), t('new'), t('change', {})]); assert.equal(r.counts.added + r.counts.removed + r.counts.changed + r.counts.unchanged, r.entries.length); });
